[config]
schemaVersion = "0.0.1"

[general]
repository = "https://github.com/Rosentti/JesterTimeout"

[package]
namespace = "Rosentti"
name = "Jester Timeout"
description = "Puts Jesters go back into their box after a configurable timeout"
websiteUrl = "https://github.com/Rosentti/JesterTimeout"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/netstandard2.1/JesterTimeout.dll"
target = "BepInEx/plugins/JesterTimeout.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods", "monsters", "tweaks", "server-side"]